### ISSUE TITLE
Channel labels go black

### ISSUE THREAD

**Issue by pwalczysko** [ome/gallery#5]
When in Full Viewer in Gallery, e.g. on ray image ID 1297, then clicking onto a channel (left hand side of the Full Viewer) to switch it off makes the button with the channel name black. When clicked back in , the channel name does not come back (instead the button stays black, until you refresh the browser)

![screen shot 2015-08-04 at 10 46 23](https://cloud.githubusercontent.com/assets/2478303/9058048/341103fa-3a96-11e5-8304-438a23c978a4.png)

![screen shot 2015-08-04 at 10 41 14](https://cloud.githubusercontent.com/assets/2478303/9058055/453461d6-3a96-11e5-8861-7848145c8248.png)

**Comment by aleksandra-tarkowska** [comment]
This is a bug in the viewer

**Comment by pwalczysko** [comment]
@aleksandra-tarkowska Yes, confirmed on trout merge.

**Comment by pwalczysko** [comment]
Created https://trac.openmicroscopy.org/ome/ticket/12981. Closing this.
